const Interests = {
  TYPESCRIPT: "Typescript",
  JAVASCRIPT: "Javascript",
  SWIFT: "Swift",
  FLUTTER: "Flutter",
  VUE: "Vue",
  NEXT_JS: "Nextjs",
  SVELTE: "Svelte",
  PHP: "PHP",
  MONGO_DB: "MongoDB",
  GO: "Go",
  SPRING: "Spring",
  NEST_JS: "Nestjs",
  KIBANA: "Kibana",
  POSTGRESQL: "PostSQL",
  PYTHON: "Python",
  GRAPHQL: "GraphQL",
  MYSQL: "MySQL",
  REACT_JS: "React",
  REACT_NATIVE: "ReactNative",
  JEST: "Jest",
  GIT: "Git",
  DOCKER: "Docker",
  GITHUB: "Github",
  KUBERNETES: "Kubernetes",
  FIGMA: "Figma",
  NODE_JS: "Nodejs",
  DJANGO: "Django",
  JAVA: "Java",
  FIREBASE: "Firebase",
  AWS: "AWS",
  GITLAB: "GitLab",
};

export default Interests;
